2024-02-26 23:02:10,485 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-26 23:02:10,485 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Configure stats pid to 8929
2024-02-26 23:02:10,485 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Loading settings from /Users/ayushdeolasee/.config/wandb/settings
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Loading settings from /Users/ayushdeolasee/Developer/brain_tumor_classification/wandb/settings
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_init.py:_log_setup():526] Logging user logs to /Users/ayushdeolasee/Developer/brain_tumor_classification/wandb/run-20240226_230210-oqplda9y/logs/debug.log
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/ayushdeolasee/Developer/brain_tumor_classification/wandb/run-20240226_230210-oqplda9y/logs/debug-internal.log
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_init.py:init():566] calling init triggers
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'revision': 1, 'dataset': 'Brain Tumour', 'epochs': 10, 'loss_function': 'Cross Entropy Loss', 'optimizer_name': 'Adam'}
2024-02-26 23:02:10,486 INFO    MainThread:8929 [wandb_init.py:init():591] re-initializing run, found existing run on stack: r50vvvdv
2024-02-26 23:02:10,487 INFO    MainThread:8929 [wandb_run.py:_finish():1970] finishing run pypdeveloper/Model V0 Revision 1/r50vvvdv
2024-02-26 23:02:10,487 ERROR   MainThread:8929 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-02-26 23:02:10,487 INFO    MainThread:8929 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-26 23:02:10,487 INFO    MainThread:8929 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-26 23:02:10,487 INFO    MainThread:8929 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-26 23:02:10,487 INFO    MainThread:8929 [wandb_run.py:_restore():2193] restore
2024-02-26 23:02:10,488 INFO    MainThread:8929 [wandb_run.py:_restore():2199] restore done
2024-02-26 23:02:18,634 INFO    MainThread:8929 [wandb_init.py:init():616] starting backend
2024-02-26 23:02:18,634 INFO    MainThread:8929 [wandb_init.py:init():620] setting up manager
2024-02-26 23:02:18,636 INFO    MainThread:8929 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-26 23:02:18,636 INFO    MainThread:8929 [wandb_init.py:init():628] backend started and connected
2024-02-26 23:02:18,638 INFO    MainThread:8929 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-26 23:02:18,638 INFO    MainThread:8929 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-26 23:02:18,638 INFO    MainThread:8929 [wandb_init.py:init():720] updated telemetry
2024-02-26 23:02:18,639 INFO    MainThread:8929 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-26 23:02:20,302 INFO    MainThread:8929 [wandb_run.py:_on_init():2262] communicating current version
2024-02-26 23:02:20,380 INFO    MainThread:8929 [wandb_run.py:_on_init():2271] got version response 
2024-02-26 23:02:20,380 INFO    MainThread:8929 [wandb_init.py:init():804] starting run threads in backend
2024-02-26 23:02:22,197 INFO    MainThread:8929 [wandb_run.py:_console_start():2241] atexit reg
2024-02-26 23:02:22,197 INFO    MainThread:8929 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-26 23:02:22,197 INFO    MainThread:8929 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-26 23:02:22,198 INFO    MainThread:8929 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-26 23:02:22,198 INFO    MainThread:8929 [wandb_init.py:init():847] run started, returning control to user process
2024-02-26 23:02:55,120 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-26 23:02:55,121 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Configure stats pid to 8929
2024-02-26 23:02:55,121 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Loading settings from /Users/ayushdeolasee/.config/wandb/settings
2024-02-26 23:02:55,121 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Loading settings from /Users/ayushdeolasee/Developer/brain_tumor_classification/wandb/settings
2024-02-26 23:02:55,121 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-26 23:02:55,121 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-26 23:02:55,121 INFO    MainThread:8929 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-26 23:02:55,121 INFO    MainThread:8929 [wandb_init.py:_log_setup():526] Logging user logs to /Users/ayushdeolasee/Developer/brain_tumor_classification/wandb/run-20240226_230255-pbd8dsvz/logs/debug.log
2024-02-26 23:02:55,122 INFO    MainThread:8929 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/ayushdeolasee/Developer/brain_tumor_classification/wandb/run-20240226_230255-pbd8dsvz/logs/debug-internal.log
2024-02-26 23:02:55,122 INFO    MainThread:8929 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2ea684e20>
2024-02-26 23:02:55,122 INFO    MainThread:8929 [wandb_init.py:init():566] calling init triggers
2024-02-26 23:02:55,122 INFO    MainThread:8929 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'revision': 1, 'dataset': 'Brain Tumour', 'epochs': 10, 'loss_function': 'Cross Entropy Loss', 'optimizer_name': 'Adam'}
2024-02-26 23:02:55,122 INFO    MainThread:8929 [wandb_init.py:init():591] re-initializing run, found existing run on stack: oqplda9y
2024-02-26 23:02:55,123 INFO    MainThread:8929 [wandb_run.py:_finish():1970] finishing run pypdeveloper/Model V0 Revision 1/oqplda9y
2024-02-26 23:02:55,123 INFO    MainThread:8929 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-26 23:02:55,123 INFO    MainThread:8929 [wandb_run.py:_restore():2193] restore
2024-02-26 23:02:55,124 INFO    MainThread:8929 [wandb_run.py:_restore():2199] restore done
2024-02-26 23:03:00,079 INFO    MainThread:8929 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-26 23:03:00,079 INFO    MainThread:8929 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-26 23:03:00,082 INFO    MainThread:8929 [wandb_run.py:_footer_sync_info():3825] logging synced files
